openid/OpenID4VC-HAIP

draft-high-assurance-profile-oid4vc-sd-jwt-vc.md
needs discussion. might not be needed because there is wallet attestation, wallet/client is not really a public client
=> add support for PKCE for OID4VCI

draft-oid4vc-haip-sd-jwt-vc.md, examples/authorization_details_sd_jwt_vc.json, examples/credential_metadata_sd_jwt_vc.json, examples/credential_request_sd_jwt_vc.json, examples/presentation_definition_sd_jwt_vc.json
A few days ago a PR was merged that changes the `type` property to `vct`, however this was not reflected in all examples and parts of the spec
=> fix: update to vct

draft-oid4vc-haip-sd-jwt-vc.md
According to:
- [OpenID4VP Section-5.1-9 ](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#section-5.1-9)
- the non-normative example reported below, 
`vp_formats_supported` belongs to the wallet metadata and not to the verifier metadata/request
````
The following is a non-normative example of client_metadata request parameter value in a request to present a SD-JWT VC.
{
"vp_formats": {
"vc+sd-jwt": {
"sd-jwt_alg_values": [
"ES256",
"ES384"
],
"kb-jwt_alg_values": [
"ES256",
"ES384"
]
}
}
}
````
for this reason this PR changed `vp_formats_supported` in `vp_formats` because it is related to verifier's metadata
=> fix: vp_formats for client metadata, not vp_formats_supported

draft-oid4vc-haip-sd-jwt-vc.md
Changes the reference to the adopted datatracker ID
=> Update status list reference

openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.md
Closes #71.
The HAIP currently defines that the response mode has to be `direct_post` with `redirect_uri`. However, using `redirect_uri` isn't allowed in the OpenID4VP spec for `direct_post`. Therefore, this PR proposes to change the Authorization Request parameter to `response_uri`.
=> Fix: Replace redirect_uri with response_uri for direct_post Response Mode

openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.md
would like to merge asap because LSP needs it.
=> remove deferred authorization because it has been deprecated in openid4vci

openid4vc-high-assurance-interoperability-profile-1_0.md
This PR updates the session transcript section:
- refer to OID4VP Annex B
fixes https://github.com/openid/oid4vc-haip/issues/135 but depends on merging https://github.com/openid/OpenID4VP/pull/374
=> update session transcript section to use oid4vp annex b

openid4vc-high-assurance-interoperability-profile-1_0.md
Once we have a new numbered of OID4VP, we should update the referenced version in HAIP. I believe it should be the next numbered draft = 24.
=> Update OID4VP version number

README.md, openid4vc-high-assurance-interoperability-profile-1_0.md
Incorrect JWE section link was pointed out by Martijn (thanks!)
=> Fix links to various sections in OID4VP + copyright year + some broken links

openid4vc-high-assurance-interoperability-profile-1_0.md
Apply updates based on running HAIP through OIDF's new tool for checking specifications meet the requirements at:
https://openid.net/wg/resources/naming-and-contents-of-specifications/
Namely:
Update spec to version 3 as we already published 2.
Add a (rather empty) security considerations (issue #163 has been created to add a fuller security considerations section)
Update the licenses section to match the one in the recentish update to the process document, see page 8 of:
https://openid.net/wp-content/uploads/2024/10/OIDF-Policy_IPR-Policy_Final_2024-10-19.pdf
=> Editorial: bump version, update notices, add sec considerations

openid4vc-high-assurance-interoperability-profile-1_0.md
=> Clarify #6.1 statements

openid4vc-high-assurance-interoperability-profile-1_0.md
Closes #13
I hope being a bit more explicit here helps.
=> Remark that trust mechanisms are out of scope

openid4vc-high-assurance-interoperability-profile-1_0.md
Closes #156
I added the RECOMMENDED part - happy to remove if WG is not comfortable with it.
=> signed issuer metadata

openid4vc-high-assurance-interoperability-profile-1_0.md
Closes #43
closes #102
closes #35
=> Key resolution options: require x509_hash, remove web based key resolution

openid4vc-high-assurance-interoperability-profile-1_0.md
https://github.com/openid/oid4vc-haip/pull/207 added stronger language, so the language here is now redundant/confusing and I think we're better off without it.
=> Remove now superfluous sentence about ephemeral client attestations

openid4vc-high-assurance-interoperability-profile-1_0.md
Closes #160
I think we should restructure some parts of haip into a separate section - e.g., move openid4vp & dcql  requirements that are shared by sd-jwt vc, dc api, mdoc profiles into their own section. I would propose to do so in a new PR once the remaining ones that are awaiting reviews are merged?
=> Mandate AKI for trusted_authorities

openid4vc-high-assurance-interoperability-profile-1_0.md
Logic behind this and based on the following that is already in the OID4VCI spec:
- if a credential configuration contains `cryptographic_binding_methods_supported`, proof(s) have to be provided
- if `nonce_endpoint` present, then wallet must provide `c_nonce` in proof(s)
- if `nonce_endpoint` present, then the issuer must check that the nonce in the proof(s) matches the provided `c_nonce`
Hence, all we need to do is to require `nonce_endpoint` to be present if there is a credential configuration that requires key binding.
Editorially, I'm not sure if the newline is required @jogu 
closes #149
=> require c_nonce for key bound creds

openid4vc-high-assurance-interoperability-profile-1_0.md
x5c is required as per https://github.com/openid/oid4vc-haip/pull/178
This leaves it unsaid what iss is actually set to. I raised https://github.com/openid/oid4vc-haip/issues/215
in case we need to say something about that but think the scope of this PR should just be removing the text that is now inconsistent with other parts of HAIP.
=> Remove now incorrect sentence about iss in SD-JWT VC

openid4vc-high-assurance-interoperability-profile-1_0.md
=> Added support for credentials without cryptographic holder binding

openid4vc-high-assurance-interoperability-profile-1_0.md
fixes #206 
partially fixes #225 but perhaps it fixes it entirely @c2bo , what do you think (since you created the issue)?
This PR refactors the OID4VP related sections to make it clear that ISO mdocs are included in the OID4VP profile defined in HAIP. Furthermore, it removes PEX references and redundant normative statements that require DCQL.
I kept the SD-JWT VC requirements for OID4VP section but tbh, after PEX got removed, there is not much to require there that is not mandated by OID4VP.
IMO, we don't even need to require the format identifier for SD-JWT VC since it is given by OID4VP but I kept it for discussion.
resolves #161 
resolves #98
=> refactor OID4VC sections to include ISO mdocs

openid4vc-high-assurance-interoperability-profile-1_0.md
Changes to additional SD-JWT VC requirements.
The pull request initially proposed solving https://github.com/openid/OpenID4VC-HAIP/issues/164 by adding `nbf` claim requirements. The discussion and the commits added into this pull request steered this pull request towards being a more general changeset for the additional SD-JWT VC requirements.
=> Changes to additional SD-JWT VC requirements

openid4vc-high-assurance-interoperability-profile-1_0.md
We had two subsections within the same section both titled "Issuer Metadata" - combine them into a single section.
closes #246
=> Editorial: Combine the two 'Issuer Metdata' sections

openid4vc-high-assurance-interoperability-profile-1_0.md
- prohibit self-signed certificates for x509_hash
- additionally, we somehow lost the preventing the trust anchor language from https://github.com/openid/OpenID4VC-HAIP/pull/238 for x509_hash; also the doc history, this PR fixes it.
Fixes #236
=> prohibit self-signed certificates for x509_hash

openid4vc-high-assurance-interoperability-profile-1_0.md
closes #239
closes #240
closes #248
=> Seperate schemes for VP/VCI, make custom uri support ecosystem decision

openid4vc-high-assurance-interoperability-profile-1_0.md
=> clarify batch issuance requirements

openid4vc-high-assurance-interoperability-profile-1_0.md
As per discussion on #247 there doesn't seem to be any known reason for this requirement to be there.
closes #247
=> Remove requirement that SD-JWT iss is a https url

openid4vc-high-assurance-interoperability-profile-1_0.md
Make it clearer we're just pointing out the existence of those sections and changing their normative status.
=> Tweak security considerations reference to OID4VP/VCI

openid4vc-high-assurance-interoperability-profile-1_0.md
The requirements to use PAR and PKCE are already present in FAPI2 so can be removed here.
closes #198
closes #283
=> Require use of (most of) FAPI2 with VCI

openid4vc-high-assurance-interoperability-profile-1_0.md
Proposal making the wallet attestations format recommended instead of mandatory. Happy to change the text if we get consensus on the wg for a different path, but this seemed to be the current outcome?
closes #211
=> Allow other Wallet Attestation formats
