- draft-oid4vc-haip-sd-jwt-vc.md
Closes # 
[click here for rendered preview of PR](https://github.com/<repo-name>/<branch-name>/<draft-name>.html)
> add reference to status list

- draft-oid4vc-haip-sd-jwt-vc.md
> remove the requirement for the JSON serialization

- draft-oid4vc-haip-sd-jwt-vc.md
Closes #30
not sure about the sentence on how to obtain scopes, but felt like something had to be said about it
> remove reference to a merged VCI PR 520

- draft-oid4vc-haip-sd-jwt-vc.md
Closes # 
[click here for rendered preview of PR](https://github.com/<repo-name>/<branch-name>/<draft-name>.html)
> changed my affiliation to sprind.org

- draft-oid4vc-haip-sd-jwt-vc.md
Reference draft-ietf-oauth-attestation-based-client-auth and draft-ietf-oauth-sd-jwt-vc.
Delete statements about PRs that have been merged.
> Mike's First Editorial Suggestions

- openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.md
> Removes old sd-jwt-vc draft reference

- openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.md
> make refresh tokens optional

- openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.md
resolves #3 
please also check if these are still the orgs we want to keep referencing and if we should remove/add any other
> add references to the orgs

- openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.md
> remove reference to a client_id_scheme parameter

- openid4vc-high-assurance-interoperability-profile-sd-jwt-vc-1_0.md
> change direct_post to direct_post.jwt

- openid4vc-high-assurance-interoperability-profile-1_0.md
Some minor typos and indenting of lists that cause some rendering problems
> editorial: indentation, small typos

- openid4vc-high-assurance-interoperability-profile-1_0.md
resolves #148 .
I honestly don't know if we need this, but it came up enough that there is an issue, so if we agree we don't need this, we should just close the issue
> clarify what is optional is optional

- openid4vc-high-assurance-interoperability-profile-1_0.md
> add key attestation to OpenID4VCI

- openid4vc-high-assurance-interoperability-profile-1_0.md
> clarify that Wallet Attestations must not contain linkable information

- README.md
> Update link to editor's copy after renaming repository

- openid4vc-high-assurance-interoperability-profile-1_0.md
an attempt to address #192 
This was the least awkward text I could come up with. And the least awkward place I could find to put it.
> dpop nonce requirements should be explicit

- openid4vc-high-assurance-interoperability-profile-1_0.md
> update reference of openid4vp to 1.0

- openid4vc-high-assurance-interoperability-profile-1_0.md
> Modified Wording for Key Attestations

- openid4vc-high-assurance-interoperability-profile-1_0.md
> remove intent to retain related text

- openid4vc-high-assurance-interoperability-profile-1_0.md
> Add guidance around key sizes

- openid4vc-high-assurance-interoperability-profile-1_0.md
> Specify image formats for credential issuer metadata

- openid4vc-high-assurance-interoperability-profile-1_0.md
resolves #191  + some clean up
is this what we wanted in this PR? I am a little surprised this must is not a requirement in the status list itself? (quickly checked but did not seem to be)
> add requirement on status list index uniqueness
